package com.zzyportals.dao;

import com.zzyportals.dataobject.DoctorDO;
import com.zzyportals.dataobject.DoctorDOKey;
import com.zzyportals.dataobject.DoctorDOWithBLOBs;

public interface DoctorDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_doctor
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int deleteByPrimaryKey(DoctorDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_doctor
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int insert(DoctorDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_doctor
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int insertSelective(DoctorDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_doctor
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    DoctorDOWithBLOBs selectByPrimaryKey(DoctorDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_doctor
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int updateByPrimaryKeySelective(DoctorDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_doctor
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(DoctorDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_doctor
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int updateByPrimaryKey(DoctorDO record);
}