package com.zzyportals.dao;

import com.zzyportals.dataobject.ResourcesRoleRefDO;
import com.zzyportals.dataobject.ResourcesRoleRefDOKey;

public interface ResourcesRoleRefDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_role_ref
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int deleteByPrimaryKey(ResourcesRoleRefDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_role_ref
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int insert(ResourcesRoleRefDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_role_ref
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int insertSelective(ResourcesRoleRefDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_role_ref
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    ResourcesRoleRefDO selectByPrimaryKey(ResourcesRoleRefDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_role_ref
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int updateByPrimaryKeySelective(ResourcesRoleRefDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_role_ref
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int updateByPrimaryKey(ResourcesRoleRefDO record);
}